version: '3.8'

services:
  medical-chatbot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-} # Allow empty CUDA devices if no GPU
    volumes:
      - ./medical_chatbot_model:/app/medical_chatbot_model
      - ./logs:/app/logs
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              optional: true # Make GPU optional
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
